[build]
  functions = "netlify/functions"
  publish = "." # raiz, já que o index.html está direto na root

[dev]
  functions = "netlify/functions"
  publish = "." # igual ao [build]

[functions]
  node_bundler = "esbuild"

# Opcional: redirecionamentos se estiver usando rotas dinâmicas no SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
